name: mad_rgz
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - jupyterlab
  - matplotlib
  - seaborn
  - plotly
  - json5
  - streamlit
  - tk
  - Pillow
  - pip
  - pip:
    - neurolab